services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-dependencies-env
    ports:
      - "5173:5173"
    command: [ "npm", "run", "dev", "--", "--host" ]
