import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/home');
  await page.getByRole('link', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search for products...' }).click();
  await page.getByRole('textbox', { name: 'Search for products...' }).fill('fr');
  await page.getByRole('slider').fill('295');
  await page.getByRole('textbox', { name: 'Search for products...' }).click();
  await page.getByRole('textbox', { name: 'Search for products...' }).fill('');
  await page.getByRole('slider').fill('1809');
  await page.getByRole('button', { name: 'GPU' }).click();
  await page.getByRole('button', { name: 'CPU', exact: true }).click();
  await page.getByRole('button', { name: 'CPU', exact: true }).click();
  await page.getByRole('button', { name: 'Memory' }).click();
  await page.getByRole('button', { name: 'Motherboard' }).click();
  await page.getByRole('button', { name: 'Power Supply' }).click();
  await page.getByRole('button', { name: 'Case' }).click();
  await page.getByRole('button', { name: 'CPU Cooler' }).click();
  await page.getByRole('button', { name: 'Storage' }).click();
  await page.getByRole('slider').fill('3000');
  await page.getByRole('button', { name: 'GPU' }).click();
  await page.getByRole('combobox').selectOption('Price: Low to High');
  await page.getByRole('combobox').selectOption('Price: High to Low');
  await page.getByRole('combobox').selectOption('Rating');
  await page.getByRole('button', { name: 'Add to Cart' }).first().click();
  await page.getByRole('button', { name: 'Add to Cart' }).nth(1).click();
  await page.getByRole('button', { name: 'Add to wishlist' }).nth(2).click();
  await page.getByRole('link', { name: 'Wishlist' }).click();
  await page.getByRole('link', { name: 'Cart' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('button').nth(2).click();
  await page.getByRole('button', { name: 'Proceed to Checkout' }).click();
  await page.getByRole('button', { name: 'Back to Cart' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('button').first().click();
});