// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/search" | "/checkout" | "/orders" | "/login";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/checkout.tsx": {
    id: "routes/checkout";
    page: "/checkout";
  };
  "routes/orders.tsx": {
    id: "routes/orders";
    page: "/orders";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/checkout": typeof import("./app/routes/checkout.tsx");
  "routes/orders": typeof import("./app/routes/orders.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
};